[tool.poetry]
name = "코딩연습"
version = "0.1.0"
description = ""
authors = ["ksw0733 <ksw0733@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
numpy = "^2.0.0"
flask = "^3.0.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
